baseURL = 'https://edw.is'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Elias Daler'

theme = 'etch'

[params]
    highlight = true
    copyright = '' # TODO: proper string
    description = "The personal website of Elias Daler about programming, technology and videogames"

[author]
    name = 'Elias Daler'
[outputFormats]
    [outputFormats.RSS]
        baseName = 'feed'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = ""
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = ""
    tabWidth = ""

disableKinds = ["taxonomy", "taxonomyTerm"]
[Taxonomies]
